//@ui5-bundle com/fidschenberger/wasteStatsApp/Component-preload.js
sap.ui.require.preload({
	"com/fidschenberger/wasteStatsApp/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/fidschenberger/wasteStatsApp/model/models"],function(e,t,i){"use strict";return e.extend("com.fidschenberger.wasteStatsApp.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"com/fidschenberger/wasteStatsApp/controller/App.controller.js":function(){sap.ui.define(["./BaseController","sap/base/Log"],function(e){"use strict";return e.extend("com.fidschenberger.wasteStatsApp.controller.App",{onInit:function(){this.wasteTypes=Object.freeze({PAPER:1,OTHER:2,GLAS:3,ORGANIC:4})}})});
},
	"com/fidschenberger/wasteStatsApp/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/m/library"],function(e,t,r){"use strict";return e.extend("com.hse24.sem.hse24-sem-apps.controller.BaseController",{getRouter:function(){return t.getRouterFor(this)},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},clone:function(e){if(null==e||"object"!=typeof e)return e;var t=e.constructor();for(var r in e){if(e.hasOwnProperty(r))t[r]=e[r]}return t}})});
},
	"com/fidschenberger/wasteStatsApp/controller/Home.controller.js":function(){sap.ui.define(["./BaseController","sap/base/Log"],function(e,t){"use strict";return e.extend("com.fidschenberger.wasteStatsApp.controller.App",{addWaste:function(){var e=this.getView().getModel("waste_items");var t=e.getProperty("/wasteItems").map(function(e){return Object.assign({},e)});var r=e.getProperty("/newWasteItem");r.date=Date.now();var s=this.clone(r);t.push(s);for(var a in r){r[a]=""}e.setProperty("/newWasteItem",r);e.setProperty("/wasteItems",t)}})});
},
	"com/fidschenberger/wasteStatsApp/i18n/i18n.properties":'title=Waste Stats App\nappTitle=Waste Stats App\nappDescription=Helps you to track your household waste\n\ninputWasteWeight=Garbage Weight\ninputWasteWeightPlaceholder=Enter garbage weight...\naddWasteButton=Add',
	"com/fidschenberger/wasteStatsApp/i18n/i18n_en.properties":'title=Waste Stats App\nappTitle=Waste Stats App\nappDescription=Helps you to track your household waste\n\ninputWasteWeightPlaceholder=Garbage Weight\ninputWasteWeightPlaceholder=Enter garbage weight...',
	"com/fidschenberger/wasteStatsApp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.fidschenberger.wasteStatsApp","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.fidschenberger.wasteStatsApp.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.74.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{},"sap.ui.table":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.fidschenberger.wasteStatsApp.i18n.i18n"}},"waste_types":{"type":"sap.ui.model.json.JSONModel","uri":"model/wasteTypes.json"},"waste_items":{"type":"sap.ui.model.json.JSONModel","uri":"model/wasteItems.json"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.fidschenberger.wasteStatsApp.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"home","target":["home"]}],"targets":{"home":{"viewName":"Home","viewId":"home","viewLevel":1,"title":"{i18n>title}"}}}}}',
	"com/fidschenberger/wasteStatsApp/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/fidschenberger/wasteStatsApp/model/wasteItems.json":'{"newWasteItem":{"type":"","weight":"","date":""},"wasteItems":[{"type":"ORGANIC","weight":1740,"date":"1582212006000"},{"type":"PAPER","weight":1341,"date":"1582212006000"}]}',
	"com/fidschenberger/wasteStatsApp/model/wasteTypes.json":'{"wasteTypes":[{"key":"ORGANIC","text":"Organic"},{"key":"PAPER","text":"Paper"},{"key":"ALUMINUM","text":"Aluminum"},{"key":"DIAPERS","text":"Diapers"},{"key":"PLASTIC","text":"Plastic"},{"key":"GLASS","text":"Glass"}]}',
	"com/fidschenberger/wasteStatsApp/view/App.view.xml":'<mvc:View\r\n\tdisplayBlock="true"\r\n\txmlns="sap.m"\r\n\txmlns:mvc="sap.ui.core.mvc"><Shell><App id="app"/></Shell></mvc:View>',
	"com/fidschenberger/wasteStatsApp/view/Home.view.xml":'<mvc:View controllerName="com.fidschenberger.wasteStatsApp.controller.Home" displayBlock="true" \n\txmlns="sap.m" xmlns:table="sap.ui.table" xmlns:core="sap.ui.core" xmlns:f="sap.f" xmlns:layout="sap.ui.layout" \n\txmlns:mvc="sap.ui.core.mvc" xmlns:viz="sap.viz.ui5.controls" xmlns:viz.feeds="sap.viz.ui5.controls.common.feeds" xmlns:viz.data="sap.viz.ui5.data" ><f:DynamicPage id="dynamicPageId" preserveHeaderStateOnScroll="true" headerExpanded="true"><f:title><f:DynamicPageTitle><f:heading><Title text="{i18n>title}" /></f:heading><f:expandedContent><Label text="This is a subheading" /></f:expandedContent><f:snappedContent><Label text="This is a subheading" /></f:snappedContent><f:snappedTitleOnMobile><Title text="{i18n>title}" /></f:snappedTitleOnMobile><f:content><OverflowToolbar><GenericTag text="SR" status="Error" press="onGenericTagPress" design="StatusIconHidden"><ObjectNumber number="2" unit="M" emphasized="false" state="Error" /></GenericTag></OverflowToolbar></f:content><f:actions><ToolbarSpacer /><Button text="Edit" type="Emphasized" /><Button text="Delete" type="Transparent" /><Button text="Copy" type="Transparent" /><Button icon="sap-icon://action" type="Transparent" /></f:actions></f:DynamicPageTitle></f:title><f:header><f:DynamicPageHeader pinnable="true"><FlexBox alignItems="Start" justifyContent="SpaceBetween"><items><Panel backgroundDesign="Transparent" class="sapUiNoContentPadding"><content><layout:HorizontalLayout class="sapUiContentPadding"><Input id="inputWasteWeight" type="Number" value="{waste_items>/newWasteItem/weight}" class="sapUiSmallMarginEnd" required="true" placeholder="{i18n>inputWasteWeightPlaceholder}" /><Select selectedKey="{waste_items>/newWasteItem/type}" forceSelection="true" items="{\n\t\t\t\t\t\t\t\t\t\t\tpath: \'waste_types>/wasteTypes\',\n\t\t\t\t\t\t\t\t\t\t\tsorter: { path: \'text\' }\n\t\t\t\t\t\t\t\t\t\t}" class="sapUiSmallMarginEnd"><core:Item key="{waste_types>key}" text="{waste_types>text}" /></Select><Button text="{i18n>addWasteButton}" press="addWaste" /></layout:HorizontalLayout></content></Panel></items></FlexBox></f:DynamicPageHeader></f:header><f:content><Table id="idWasteItemsTable" inset="false" items="{\n\t\t\t\tpath: \'waste_items>/wasteItems\',\n\t\t\t\tsorter: {\n\t\t\t\t\tpath: \'date\'\n\t\t\t\t}\n\t\t\t}"><columns><Column><Text text="Type" /></Column><Column><Text text="Weight" /></Column><Column><Text text="Date added" /></Column></columns><items><ColumnListItem><cells><Text text="{waste_items>type}" /><Text text="{waste_items>weight}" /><Text text="{\n\t\t\t\t\t\t\t\t\tpath: \'waste_items>date\',\n\t\t\t\t\t\t\t\t\ttype: \'sap.ui.model.type.DateTime\',\n\t\t\t\t\t\t\t\t\tformatOptions: { \n\t\t\t\t\t\t\t\t\t\tstyle : \'medium\',\n\t\t\t\t\t\t\t\t\t\tsource: {pattern: \'timestamp\'}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}" /></cells></ColumnListItem></items></Table></f:content></f:DynamicPage></mvc:View> \n'
});
